import { StyleSheet } from '@react-pdf/renderer'

export const colors = {
  black: '#0A0A0B',
  white: '#FFFFFF',
  offWhite: '#FAFAF8',
  smoke: '#F4F2EF',
  champagne: '#C9A96E',
  champagneLight: '#E8D5B0',
  champagneDark: '#A8873F',
  warmLight: '#F2E8E0',
  warmMid: '#E6D3BC',
  gray100: '#F8F7F5',
  gray200: '#EFEFED',
  gray400: '#B0ADA8',
  gray600: '#6B6864',
  gray900: '#121110',
}

export const styles = StyleSheet.create({
  page: {
    backgroundColor: colors.offWhite,
    paddingTop: 48,
    paddingBottom: 60,
    paddingHorizontal: 52,
    fontFamily: 'Helvetica',
  },
  coverPage: {
    backgroundColor: colors.black,
    paddingHorizontal: 52,
    paddingVertical: 48,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionLabel: {
    fontSize: 8,
    textTransform: 'uppercase',
    letterSpacing: 3,
    color: colors.champagne,
    marginBottom: 8,
    fontFamily: 'Helvetica-Bold',
  },
  h1: {
    fontSize: 28,
    fontFamily: 'Helvetica-Bold',
    color: colors.black,
    lineHeight: 1.2,
    marginBottom: 8,
  },
  h2: {
    fontSize: 20,
    fontFamily: 'Helvetica-Bold',
    color: colors.black,
    lineHeight: 1.3,
    marginBottom: 6,
  },
  h3: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
    color: colors.black,
    lineHeight: 1.4,
    marginBottom: 4,
  },
  body: {
    fontSize: 11,
    color: colors.gray900,
    lineHeight: 1.65,
    marginBottom: 6,
    fontFamily: 'Helvetica',
  },
  bodySmall: {
    fontSize: 9,
    color: colors.gray600,
    lineHeight: 1.6,
    fontFamily: 'Helvetica',
  },
  bulletItem: {
    flexDirection: 'row',
    fontSize: 11,
    color: colors.gray900,
    marginBottom: 6,
    fontFamily: 'Helvetica',
  },
  bulletDot: {
    color: colors.champagne,
    marginRight: 10,
    fontSize: 14,
    fontFamily: 'Helvetica',
  },
  calloutPro: {
    backgroundColor: colors.warmLight,
    borderLeftWidth: 3,
    borderLeftColor: colors.champagne,
    padding: 16,
    borderRadius: 4,
    marginVertical: 16,
  },
  calloutWarning: {
    backgroundColor: '#FEF3F2',
    borderLeftWidth: 3,
    borderLeftColor: '#E53E3E',
    padding: 16,
    borderRadius: 4,
    marginVertical: 16,
  },
  calloutCritical: {
    backgroundColor: '#FFFBEB',
    borderLeftWidth: 3,
    borderLeftColor: colors.champagneDark,
    padding: 16,
    borderRadius: 4,
    marginVertical: 16,
  },
  checklist: {
    marginVertical: 12,
  },
  checklistItem: {
    flexDirection: 'row',
    marginBottom: 8,
    alignItems: 'flex-start',
  },
  checklistBox: {
    width: 14,
    height: 14,
    borderWidth: 1,
    borderColor: colors.gray400,
    marginRight: 10,
    marginTop: 1,
    borderRadius: 2,
  },
  divider: {
    height: 0.5,
    backgroundColor: colors.champagneLight,
    marginVertical: 24,
  },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 52,
    right: 52,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pageNumber: {
    fontSize: 8,
    color: colors.gray400,
    fontFamily: 'Helvetica',
  },
  brandMark: {
    fontSize: 8,
    color: colors.champagne,
    letterSpacing: 2,
    textTransform: 'uppercase',
    fontFamily: 'Helvetica',
  },
})
